Adding back check for fixable and add additional tests

diff --git a/.github/workflows/test-action-failure-policy.yaml b/.github/workflows/test-action-failure-policy.yaml
--- a/.github/workflows/test-action-failure-policy.yaml
+++ b/.github/workflows/test-action-failure-policy.yaml
@@ -12,6 +12,7 @@ jobs:
         run: docker image pull ghcr.io/timarenz/vulnerable-container:v0.0.1
 
       - name: lw-scanner
+        id: lw-scanner
         uses: ./
         continue-on-error: true
         with:
@@ -22,3 +23,7 @@ jobs:
           SAVE_BUILD_REPORT: true
           BUILD_REPORT_FILE_NAME: report.html
           USE_POLICY: true
+
+      - name: Check if vulnerabilites were found and step failed.
+        if: steps.lw-scanner.outcome == 'failure'
+        run: echo "Vulnerabilities found and step failed succesfully." && exit 1
