Add missing jq if required

diff --git a/.github/workflows/test-action-failure-critical.yaml b/.github/workflows/test-action-failure-critical.yaml
--- a/.github/workflows/test-action-failure-critical.yaml
+++ b/.github/workflows/test-action-failure-critical.yaml
@@ -3,7 +3,7 @@ on:
   push:
   workflow_dispatch:
   schedule:
-    - cron: '30 8 * * *'
+    - cron: "30 8 * * *"
 
 jobs:
   test-action-failure-critical:
@@ -29,6 +29,10 @@ jobs:
           FAIL_BUILD: true
           SEVERITY_THRESHOLD: critical
 
+      - name: Check if action failed for any other reason then vulnerabilities found.
+        if: steps.lw-scanner.outputs.EXIT_CODE != '1'
+        run: echo "Action failed." && exit 1
+
       - name: Check if vulnerabilites were found and step failed.
-        if: steps.lw-scanner.outcome == 'failure'
+        if: steps.lw-scanner.outputs.EXIT_CODE == '1'
         run: echo "Vulnerabilities found and step failed succesfully." && exit 0
